AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Master data management for employees

Globals:
  Function:
    # Runtime: nodejs6.10
    # Timeout: 3
    # Handler: index.handler
    # MemorySize: 128
    Tags:
      CostCenter: Tecco
      Owner: dschmitz
  # Tracing:
  # DeadLetterQueue:
  # DeploymentPreference:
    # Enabled: true
    # Type: Linear10PercentEvery10Minutes
    # Alarms:
    #   # A list of alarms that you want to monitor
    #   - !Ref AliasErrorMetricGreaterThanZeroAlarm
    #   - !Ref LatestVersionErrorMetricGreaterThanZeroAlarm
    # Hooks:
    #   # Validation Lambda functions that are run before & after traffic shifting
    #   PreTraffic: !Ref PreTrafficLambdaFunction
    #   PostTraffic: !Ref PostTrafficLambdaFunction
  # AutoPublishAlias

Parameters:
  NamePrefix:
    Type: String
    Default: "Fis2_0-Employees-"
  # CodeLocation:
  #   Type: String
  #   # Default: "build/employee.zip"

Resources:
  GetEmployeesRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${NamePrefix}GetEmployeesRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
      ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSLambdaExecute
          - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess

  GetEmployees:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Timeout: 3
      MemorySize: 128
      FunctionName: !Sub "${NamePrefix}GetEmployees"
      Description: "Get all known employees"
      CodeUri: .
      Handler: index.getAll
      Role: !GetAtt GetEmployeesRole.Arn
      Tracing: Active
      Events:
        ListEmployees:
          Type: Api
          Properties:
            Path: /employee
            Method: get

  GetEmployee:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Timeout: 3
      MemorySize: 128
      FunctionName: !Sub "${NamePrefix}GetEmployee"
      Description: "Get employee by id"
      CodeUri: .
      Handler: index.getById
      Role: !GetAtt GetEmployeesRole.Arn
      Tracing: Active
      Events:
        GetEmployee:
          Type: Api
          Properties:
            Path: /employee/{id}
            Method: get

  GetContractByEmployee:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Timeout: 3
      MemorySize: 128
      FunctionName: !Sub "${NamePrefix}GetContractByEmployee"
      Description: "Get contract for an employee"
      CodeUri: .
      Handler: index.getContractByEmployee
      Role: !GetAtt GetEmployeesRole.Arn
      Tracing: Active
      Events:
        GetEmployee:
          Type: Api
          Properties:
            Path: /employee/{id}/contract
            Method: get


  # GetEmployeeById:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Timeout: 1
  #     Runtime: nodejs6.10
  #     Handler: index.getById
  #     CodeUri: .

# Outputs: