AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Master data management for employees

Globals:
  Function:
    Runtime: nodejs6.10
    Timeout: 3
    Handler: index.handler
    CodeUri: build/employee.zip
    MemorySize: 128
    Tags:
      CostCenter: Tecco
      Owner: dschmitz
  # Tracing:
  # DeadLetterQueue:
  # DeploymentPreference:
    # Enabled: true
    # Type: Linear10PercentEvery10Minutes
    # Alarms:
    #   # A list of alarms that you want to monitor
    #   - !Ref AliasErrorMetricGreaterThanZeroAlarm
    #   - !Ref LatestVersionErrorMetricGreaterThanZeroAlarm
    # Hooks:
    #   # Validation Lambda functions that are run before & after traffic shifting
    #   PreTraffic: !Ref PreTrafficLambdaFunction
    #   PostTraffic: !Ref PostTrafficLambdaFunction
  # AutoPublishAlias

Parameters:
  NamePrefix:
    Type: String
    Default: "Fis2_0-Employees-"

Resources:
  GetEmployeesRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${NamePrefix}GetEmployeesRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
      ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSLambdaExecute

  GetEmployees:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${NamePrefix}GetEmployees"
      Description: "Get all known employees"
      CodeUri: build/employee.zip
      Handler: index.getAll
      Role: !GetAtt GetEmployeesRole.Arn

  # GetEmployeeById:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Timeout: 1
  #     Runtime: nodejs6.10
  #     Handler: index.getById
  #     CodeUri: .

# Outputs: